plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

theme: jekyll-theme-minimal
title: Mozilla Voice Community Playbook
description: https://voice.mozilla.org
logo: /assets/img/logo.png
show_downloads: true
